on: [push]
name: Hacks
jobs:


  meta-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euo pipefail {0}
    steps:
    - uses: actions/checkout@v6
    - run: ./hack/clis.sh | tee .github/workflows/clis.yml
    - run: ./hack/self.sh | tee .github/workflows/self.yml
    - run: ./hack/docs.sh
    - run: git --no-pager diff --exit-code
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        check_together: 'yes'
        severity: error


  hit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: ./hack/hit.sh


  portable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: ./hack/portable.sh


  latest_buildkit:
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        shell: bash -euo pipefail {0}
    steps:
    - uses: actions/checkout@v6
    - run: ./hack/latest_buildkit.sh | tee cargo-green/src/latest_buildkit.txt
    - run: git --no-pager diff --exit-code -- cargo-green/src/latest_buildkit.txt || echo "::warning file=cargo-green/src/latest_buildkit.txt,line=1,col=1::New version out"


  caching:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euo pipefail {0}
    steps:
    - uses: docker/login-action@v3
      if: ${{ ! startsWith(github.ref, 'refs/heads/dependabot/') }}
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker info
    - run: docker buildx version
    - run: docker buildx build --help
    - run: podman version || true
    - run: cargo -Vv
    - run: docker buildx prune --all --force
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        rustflags: ''
        cache-all-crates: true
        cache-workspace-crates: true

    - uses: actions/checkout@v6

    - name: Cache `cargo fetch`
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ github.job }}-${{ runner.os }}-cargo-deps-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ github.job }}-${{ runner.os }}-cargo-deps-

    - name: Cache `cargo install`
      uses: actions/cache@v5
      with:
        path: ~/instmp
        key: ${{ runner.os }}-cargo-install-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-install-

    - run: |
            # Usually auto-set by actions-rust-lang/setup-rust-toolchain@v1
            # https://github.com/actions-rust-lang/setup-rust-toolchain/blob/fb51252c7ba57d633bc668f941da052e410add48/action.yml#L105
            unset CARGO_INCREMENTAL
            unset CARGO_PROFILE_DEV_DEBUG
            unset CARGO_REGISTRIES_CRATES_IO_PROTOCOL
            unset CARGO_TERM_COLOR
            unset CARGO_UNSTABLE_SPARSE_REGISTRY
            unset RUST_BACKTRACE
            unset RUSTFLAGS

            ./hack/caching.sh
    # - run: git --no-pager diff --cached --exit-code -- recipes/buildxargs@1.4.0.Dockerfile  #TODO: enable whence https://github.com/fenollp/supergreen/pull/151
